# Generated by Django 4.0 on 2022-12-07 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelperCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Helper Categorie',
                'verbose_name_plural': 'Helper Categories',
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('extra', models.CharField(max_length=300)),
                ('helper_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.helpercategorie')),
            ],
            options={
                'verbose_name': 'Helper',
                'verbose_name_plural': 'Helpers',
            },
        ),
    ]
