# Generated by Django 4.0 on 2022-12-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
