# Generated by Django 4.0 on 2022-12-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_alter_helper_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='extra',
            field=models.CharField(max_length=500),
        ),
    ]
