# Generated by Django 4.0 on 2022-01-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_name', models.CharField(max_length=250, verbose_name='Catalog name')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=400, verbose_name='Product name')),
                ('product_price', models.FloatField(verbose_name='Product price')),
                ('product_description', models.TextField(null=True)),
                ('catalog_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.catalog', verbose_name='Catalog name')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
    ]
