# Generated by Django 4.0 on 2022-01-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catalogproduct_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='catalogproduct',
            options={'verbose_name': 'Catalog product', 'verbose_name_plural': 'Catalog products'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=400),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product-images', verbose_name='Product image'),
        ),
    ]
